project_id = "qivpavmnxipijtrlfrqt"

[functions.get-weather]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.fetch-mandi-prices]
verify_jwt = false

[functions.update-market-prices]
verify_jwt = false